### ISSUE TITLE
NMMNHS Welcome to Arctos

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#105]
Send Welcome email to new collection
https://drive.google.com/file/d/1poLg-4ObBjsW5pmaOd8tUIvHlBOtIG54/view

**Comment by AJLinn** [comment]
Hey @Jegelewicz  I'm trying to figure out which collection this is to get the contact info to reach out. Is it the UNM (New Mexico earth sciences)?

**Comment by jldunnum** [comment]
New Mexico Museum of Natural History and Science, its the state museum here in NM.


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by AJLinn** [comment]
Thanks @jldunnum!
@Jegelewicz I'm not seeing any folder in the Arctos Google Drive (Arctos-Shared/Collections - Forms, MOUs, Contacts) for their collection in order to get a welcome letter to them.

**Comment by campmlc** [comment]
Hi Angie,
Michelle and I just updated it: here is the link
https://docs.google.com/document/d/1IR4yt0oQe_GnyYayTBuXRVNO8s4ytf7b3tAm-L13ZsU/edit?usp=sharing
It's in Arctos Shared: Communications, Outreach, Webinars folder.

**Comment by Jegelewicz** [comment]
@AJLinn I will email you contact info.

**Comment by Jegelewicz** [comment]
@AJLinn I just uploaded the final MOU to the [Google Drive](https://drive.google.com/open?id=1wfrEjd739LPjjadOLwByGlinR9uRyRJj)

**Comment by Jegelewicz** [comment]
Send to Lindsey and Nicole Ridgwell: Nicole.Ridgwell@state.nm.us

Please cc Mariel

Check in if they don't contact you to make sure they have what they need. Maybe invite Lindsey to attend the next AWG meeting.

**Comment by AJLinn** [comment]
done!
