### ISSUE TITLE
NMMNHS Institution Acronym

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#106]
Institution to register at GRBIO http://grbio.org/

**Comment by Jegelewicz** [comment]
The first step in the process is to determine the GUID prefixes for your collections.

    GUID_PREFIX is traditionally institution_acronym + ":" + collection_cde and must be unique within Arctos.  GUID_PREFIX should also be unique within GRBIO/GBIF/etc. The maximum length is 20 characters.


NMMNH Mammals are published to GBIF with last ingestion on 7 October 2017 and the prefix NMMNH:Mammals. Given that, I propose that you use the following as your GUID prefixes:

Amphibians and Reptiles: if one collection NMMNH:Herp, if separate collections NMMNH:Amph and NMMNH:Rept
Fishes: NMMNH:Fish
Birds: NMMNH:Bird
Mammals: NMMNH:Mammals
Insects: NMMNH:Ento
Invertebrates: NMMNH:Inv
Tissues: NMMNH:Tissue (or should the tissues just be parts in the other collections? You should discuss this with Mariel)
Herbarium: NMMNH:Herb
Paleontology: NMMNH:ES
Earth Sciences: if you have other geology collections besides paleo, I suggest using NMMNH:Geol but we should probably discuss this in more detail.

Once we have agreed upon the GUID Prefixes, Mariel or I can get the forms set up to create your collections. This will involve some additional information required from you which you can start gathering now if you like. This will include:

1. A description of each collection. Maximum length is 4000 characters
2. A URL to more information, such as the collection's home page at NMMNHS
3. The clickable text to display with the above web link
4. Select a license to govern the usage of your data in Arctos. Note that data shared via DWC may be licensed differently, and Media are individually licensed.You can see the list of available licenses here.
5. The catalog number format for each collection. Most collections use simple integers, however Arctos can accommodate alphanumeric catalog numbers. I don't recommend them if at all possible because they make searching and sorting much more difficult. You can read the documentation on catalog numbers in Arctos here.
6. A URL to each collection's loan policy. A loan policy is required; the contents of the loan policy are entirely up to you. If you need assistance in creating or hosting a loan policy, please let me know.
7. Select a Taxonomy Source for each collection. This will be "your" classification system. You can choose an existing source (Arctos for animals Arctos Plants for plants), you can import data for your own classification system, or you can use an external source.Currently, everyone in Arctos is using the existing sources. If you want to choose one of the other options, we will need to work through the process of getting your Taxonomy set up before you can import data. Let me know if you have any questions about this.
8. A list of Arctos username(s) and email addresses for anyone who will receive initial manage_collection access. Anyone at OWU who will be managing one of the collections should create a user account in Arctos. Instructions for creating an account can be found here.

Let me know if you have any questions. As soon as I get your approval for the GUID Prefixes, I'll open the create collection forms and have you complete them with the information you have gathered above.

Adios,

**Comment by dustymc** [comment]
> Mammals: NMMNH:Mammals

That's certainly not a technical problem, and users should not be typing identifiers anyway, but it would create a situation where we have 25 "xxx:Mamm" collections and one "xxx:Mammals," which I would expect to cause some confusion and communication difficulties.

**Comment by Jegelewicz** [comment]
From Lindsey:

> This is great!
> So far this is what me and Nicole have discussed:
> 
> Amphibians and Reptiles:       NMMNH:Herp
> Fishes:                                     NMMNH:Fish
> Birds:                                      NMMNH:Bird
> Mammals:                                NMMNH:Mamm
> Insects:                                    NMMNH:Ento
> Invertebrates:                          NMMNH:Inv
> Herbarium:                              NMMNH:Herb
> 
> Vertbrate Paleo:          NMMNH:VPaleo
> Inertebrate Paleo:        NMMNH:IPaleo
> Trace Fossils:               NMMNH:TPaleo
> Minerals:                     NMMNH:Geol
> 
> We would like to split our paleontology collections up into three separate portals.  In particular we would like to separate the trace fossils because they use a separate taxonomy from the other groups.  Invertebrates and vertebrates are also typically separated within paleo collections and research. We would then also like a separate portal for our minerals. We have come up with some preliminary names in red, so please let us know what you think.
> 
> Are also able to add portals later? Like an observation portal?
> 
> Thanks
> 
> Lindsey and Nicole

**Comment by Jegelewicz** [comment]
Lindsey,

No problem adding portals later, this often happens once an institution realizes what they can do with Arctos! The separate paleo collections make perfect sense and the collection codes you have chosen should work just fine. The trace fossils will be a new collection type for Arctos so before choosing a taxonomy for that collection, we should probably have a discussion about what is needed.

I'll work on getting the forms set up for these portals then we can add the information that I detailed in my last email.

Thanks!
