### ISSUE TITLE
NMMNHS Collection Portal Request

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#107]
Institution contact requests collection portal creation. Please use the form at Reports/CollectionCreationRequest or http://arctos.database.museum/new_collection.cfm

**Comment by Jegelewicz** [comment]
> So far this is what me and Nicole have discussed:
> 
> Amphibians and Reptiles:       NMMNH:Herp
> Fishes:                                     NMMNH:Fish
> Birds:                                      NMMNH:Bird
> Mammals:                                NMMNH:Mamm
> Insects:                                    NMMNH:Ento
> Invertebrates:                          NMMNH:Inv
> Herbarium:                              NMMNH:Herb
>  
> Vertbrate Paleo:          NMMNH:VPaleo
> Inertebrate Paleo:        NMMNH:IPaleo
> Trace Fossils:               NMMNH:TPaleo
> Minerals:                     NMMNH:Geol
> 
> We would like to split our paleontology collections up into three separate portals.  In particular we would like to separate the trace fossils because they use a separate taxonomy from the other groups.  Invertebrates and vertebrates are also typically separated within paleo collections and research. We would then also like a separate portal for our minerals. We have come up with some preliminary names in red, so please let us know what you think.
> 
> Are also able to add portals later? Like an observation portal?
> 
> Thanks

Lindsey and Nicole

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> 
> Once we get the portals set up and start importing data, we’re also going to want to start uploading media, possibly including 3D image files.  How does it work to apply for media storage through TACC?
> 
> Thanks,

Nicole Ridgwell
Geoscience Collections Manager
New Mexico Museum of Natural History and Science

**Comment by Jegelewicz** [comment]
> Nicole,
> 
> Do you have any idea how many terabytes of storage you will need?  For exceptionally large media requirements additional media storage can be arranged through TACC for around $125/TB/year, or sourced from elsewhere. 
> 
> You might also consider uploading your 3D images to MorphoSource, which is a digital repository where researchers, museum curators, and the general public can find, download, and upload 3D media representing physical objects, most commonly biological specimens. Records on MorphoSource can be linked directly to the related Arctos specimen record. You can see an example with this Museum of Vertebrate Zoology specimen. You will find the link to MorphoSource in the Identifiers section of the specimen record.
> 
> Please let me know if you have any further questions.
> 
> Thank you,
> 

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by Jegelewicz** [comment]
Collections pre-created today.

Amphibians and Reptiles: NMMNH:Herp
Fishes: NMMNH:Fish
Birds: NMMNH:Bird
Mammals: NMMNH:Mamm
Insects: NMMNH:Ento
Invertebrates: NMMNH:Inv
Herbarium: NMMNH:Herb
Vertebrate Paleo: NMMNH:VPaleo
Invertebrate Paleo: NMMNH:IPaleo
Trace Fossils: NMMNH:TPaleo
Fossil Casts: NMMNH:CPaleo
Minerals: NMMNH:Geol

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> 
> Before we get this set up, I’m reevaluating whether our paleontology specimens need to be separated into different portals. The original reason I thought they might need to be separated was because of taxonomies, however as I’m looking through the handbook, it seems like the main Arctos taxonomy tree is set up to handle all of paleo? My main concern would be with how ichnofossil taxa are handled – when I logged into the github for the first time last week I noticed a thread about that exact topic and it seems like there may not be a good way to handle those yet?
> 
> If we did use separate portals, will those collections be able to share a locality table? Is there an ability to connect two specimens in two different portals (for example a plant and vertebrate) if they are preserved on the same slab of rock?
> 
> Thank you,

Nicole

**Comment by Jegelewicz** [comment]
> Nicole,
> 
> >    it seems like the main Arctos taxonomy tree is set up to handle all of paleo? My main concern would be with how ichnofossil taxa are handled – when I logged into the github for the first time last week I noticed a thread about that exact topic and it seems like there may not be a good way to handle those yet?
> 
> 
> Separating the paleo portals is a "personal" decision. The New Mexico Museum of Natural History will be coming in to Arctos soon and they have created separate paleo portals for vertebrate fossils, invertebrate fossils, tracks, and casts. There is no reason all of these can't be in a single portal, but that is the way they have traditionally cataloged them, so that is what they have chosen to do. As for ichnofossil taxa, I am not a paleo expert, but what I understand is that these are "placeholder" names. Any name can be created in Arctos and if we need new classification ranks, we can figure that out as a community. This is definitely something we are working to perfect. If you haven't, please follow this [GitHub issue](https://github.com/ArctosDB/arctos/issues/1900).
> 
> >     If we did use separate portals, will those collections be able to share a locality table? Is there an ability to connect two specimens in two different portals (for example a plant and vertebrate) if they are preserved on the same slab of rock? 
> 
> Yes to all. Localities are shared by ALL collections in Arctos and you can add the relationship of "collected with" or "same individual as" among other relationships between any two Arctos specimens in ANY Arctos collections (see the relationships in this [MVZ:Bird specimen](http://arctos.database.museum/guid/MVZ:Bird:134762)). I am considering what relationship we need for the scenario you describe above and how best to catalog such items and I hope to have a good solution that all the paleo collections can agree upon soon. I am working through it with the community in the GitHub issue mentioned above.
> 
> Hope that all helps! PLease let me know if anything needs to be clarified. I had a great talk with Russell last week - he's got a lot on his plate!
> 
> Adios,

Teresa

**Comment by dustymc** [comment]
Ichnotaxa are "real" - they are not placeholders. They're regulated by ICZN and the "Arctos" classification is generally "ICZN stuff."

**Comment by Jegelewicz** [comment]
Cool. Then they aren't a problem, but everyone seems to think they are....

**Comment by Jegelewicz** [comment]
@dustymc I met with these guys yesterday and I am ready to set their collections portals to be created EXCEPT they decided to put all of their paleo stuff in one portal rather than split it up into four. I don't have a way to delete the three that they have decided not to use. I changed their GUID Prefixes to DELETE, DELETE2, and DELETE3. Let me know if you want to get rid of them before I change the status for all of the portal requests to "approve to create" or if I can just tell Lam to ignore those when she gets the request to create. Thanks!

**Comment by dustymc** [comment]
>DELETE, DELETE2, and DELETE3

That should work.

**Comment by Jegelewicz** [comment]
Collections approved for creation.

**Comment by Jegelewicz** [comment]
Portals up and running.
