### ISSUE TITLE
NMMNHS GitHub and AWG membership

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#108]
Collection mentor to assist with Github registration if not already done; access to issues, documentation.

**Comment by Jegelewicz** [comment]
Nicole on GitHub and participating. Need to get Lindsey on board.

**Comment by Jegelewicz** [comment]
> Lindsey and Nicole,
> 
> Your portals are up and running, YAY! Nicole is already contributing to conversations on GitHub and I would like Lindsey to join as well. Nicole, can you help her create an account and let me know her user name? I'll add her to the Arctos user group so that she can post issues when necessary.
> 
> I would also like both of you to be part of the Arctos Working Group. We meet twice a month and you can join in any of the meetings that suit you. We communicate about meetings and Arctos outages via a Google Group. Please follow this link and request to join: https://groups.google.com/forum/#!forum/arctos-working-group
> 
> Last but not least, I would like for you guys to work with me in creating a "Migration to Arctos" workflow. Are you willing? My plan is to set up a new repository in GitHub where we can manage the steps of data migration. I will also write documentation for the process as we go along so that the next new incoming collection will have something to follow.
> 
> So happy to have you here!!!
> 
> Adios,
> 

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by Jegelewicz** [comment]
> Thanks. I’ve already made a Github account and follow the Arctos conversations. Not sure if I was ever added though so I guess it’s good to confirm. My username is lin-fred
> 
> I think Nicole and I were already added to the working group? I remember getting an invite and adding my state email, is there a way to confirm? I can’t seem to request to join with my state email so I can’t seem to confirm on my end.
> 
> And yes! A migration workflow would be great. Let us know what we need to do.
> 
> Thanks

Lindsey

**Comment by Jegelewicz** [comment]
> Lindsey and Nicole,
> 
> I invited Lindsey join the Arctos user team in GitHub, so be sure to accept that invite. Also, Nicole is in the Google group, but Lindsey is not, I'll see if I can figure that one out for you.
> 
> I have started your workflow projects in GitHub and assigned two things to Nicole. Once Lindsey is a member of the user team, I can assign tasks to her as well.  From this point, we should use the GitHub issues to communicate about data migration so that if I am unable to answer something either Mariel, Dusty, or someone else can help us out.
> 
> You will find all of the projects for your collections at https://github.com/ArctosDB/data-migration/projects
> 
> It's time to Manage your collections!

Teresa

**Comment by Jegelewicz** [comment]
@AJLinn can you help me figure out if Lindsey Frederick is in the Arctos Working Group Google Group? If she isn't, can you invite her, please?

Lindsey.Frederick@state.nm.us

Thanks!

**Comment by AJLinn** [comment]
Sorry for the delay. Lindsey is part of the Arctos group but I (as arctos.membership@gmail.com) do not have permission to manage membership in the AWG google group. I believe @dustymc has control of that one.

**Comment by Jegelewicz** [comment]
> but I (as arctos.membership@gmail.com) do not have permission to manage membership in the AWG google group. I believe @dustymc has control of that one.

@dustymc @mkoo ?

**Comment by dustymc** [comment]
You're a manager now.

**Comment by Jegelewicz** [comment]
Me or @AJLinn ?

**Comment by dustymc** [comment]
arctos.membership@gmail.com - and they should be able to give that to anyone else who wants it.

**Comment by AJLinn** [comment]
> > @AJLinn can you help me figure out if Lindsey Frederick is in the Arctos Working Group Google Group? If she isn't, can you invite her, please?
> 
> Lindsey.Frederick@state.nm.us
> 
> Thanks!

That email address failed. I used the second one listed in her agent profile (lfrede01@unm.edu) and it sent.

**Comment by campmlc** [comment]
Angie, she isn't at UNM anymore. Lindsey, is your state firewall preventing
you from getting the invites? Did Nicole's work?

**Comment by jldunnum** [comment]
This is what I have for her.

lindsey.frederick@state.nm.us


______________________________________________________________

Jonathan L. Dunnum Ph.D.
Senior Collection Manager
Division of Mammals, Museum of Southwestern Biology
University of New Mexico
Albuquerque, NM 87131
(505) 277-9262
Fax (505) 277-1351

MSB Mammals website: http://www.msb.unm.edu/mammals/index.html
Facebook: http://www.facebook.com/MSBDivisionofMammals

Shipping Address:
Museum of Southwestern Biology
Division of Mammals
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131
________________________________

**Comment by AJLinn** [comment]
> > This is what I have for her.
> 
> lindsey.frederick@state.nm.us

Yup, that's what I used. Google group won't send - 
<img width="519" alt="Screen Shot 2019-03-26 at 4 00 23 PM" src="https://user-images.githubusercontent.com/17605945/55041091-4d520400-4fe0-11e9-821b-c09937273bb8.png">

**Comment by AJLinn** [comment]
> Did Nicole's work?
Nicole is already listed as a member of the AWG google group. 
I just added Lindsey as a "direct-add" so hopefully she can get the messages now.

**Comment by lin-fred** [comment]
It seems the direct-add worked. Thank you! 

![image](https://user-images.githubusercontent.com/19802479/55080545-f3931d80-5063-11e9-85cd-cb6191a694b3.png)

**Comment by Jegelewicz** [comment]
Yay! Thanks everyone!
