### ISSUE TITLE
UMZM Collection Portal Request

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#116]
Institution contact requests collection portal creation. Please use the form at Reports/CollectionCreationRequest or http://arctos.database.museum/new_collection.cfm

**Comment by Jegelewicz** [comment]
Sent email
Libby,

Hello! I was working through some billing information and I see that you do not yet have collection portals set up. Whe you are ready to set up your portals in Arctos, Please complete the form at Reports/CollectionCreationRequest or http://arctos.database.museum/new_collection.cfm You will need to be logged in to Arctos to complete the form.

Carla is out for a few days. If you have any questions or need anything, just let me know!

Thanks!

**Comment by Jegelewicz** [comment]
Hi Teresa,

Perfect timing since I just sent what I hope will be the final version of the UMZM database to VertNet and the next step will be setting up the Arctos collection!

Looks like that form has changed since I filled it out some time ago - let me know if you have any issues with it.

Also - has John Demboski had a chance to sign the MOU between UMZM and Arctos? If so, could you forward me a copy of the signed document for my records?

Thanks!
- Libby

**Comment by Jegelewicz** [comment]
Libby,

One of the first things we need to do in setting up your collections in Arctos is to be sure we have the correct institution acronym. Arctos catalog numbers consist of three parts:

Institution Acronym:Collection Code:catalog number

I feel pretty certain that your institution acronym is UMZM, but before I set that in Arctos, I want to make sure that is what you expect.

Your collection codes will be Bird and Mamm, so you will have UMZM:Bird and UMZM:Mamm.

Let me know if any of that is incorrect or if you have questions.

Adios,

**Comment by Jegelewicz** [comment]
Libby,

Great! I have pre-created your collections. Now I need you to fill in the meta-data for each of them. You are one of the first to do this under our new system, so if anything is difficult to understand or doesn't work the way you think it should, please let me know!

Log in to Arctos and return to the initial form. Scroll down and you will see the two collections each with some fields that you need to complete. Take a look and let me know if you have any questions. The fields in yellow are required so you won't be able to save any changes unless all yellow fields are completed. If you want to walk through this with me on the phone, just let me know and we can set up a call.

Thank you!

**Comment by lkvoong** [comment]
If everything is ready to create the collections, please update the status to "approve_to_create_collections" so the system will  notify me to create the collection.  I have created the collections, but I can't update the status to complete until the status gets updated to "approve_to_create_collections" first.

Thanks!

**Comment by Jegelewicz** [comment]
I did that this morning, but it doesn't seem to have saved? @dustymc what am I doing wrong?

**Comment by Jegelewicz** [comment]
Portals created: https://arctos.database.museum/home.cfm#UMZM
![image](https://user-images.githubusercontent.com/5725767/43609206-96f7c3ae-9660-11e8-93ac-cab880bb1f88.png)

**Comment by lkvoong** [comment]
FYI: I still need to create the multi-collection portal, which I will try to get to later this afternoon.
