### ISSUE TITLE
UMZM Data Migration

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#118]
Begin data migration; forward to VertNet migrators or pre-bulkloader as determined during initial evaluation; collection contact should remain in the loop during migration process, monthly check in by collection mentor.

**Comment by Jegelewicz** [comment]
July 18 email
@dbloom just passed data to @dustymc  from UMZM (Verts).

**Comment by Jegelewicz** [comment]
Hi Dusty,

> I just wanted to check in to see if you need anything from me to migrate the UMZM database onto Arctos. At Teresa’s suggestion, I completed the new collection form through the Arctos portal last Wednesday. Are there other pieces I need to take care of?
> 
> The migration needs to be complete by August 31, 2018 – that is my LAST day at UMZM! Given this hard deadline, please let me know if I can do anything to make sure we complete the project.
> 
> Thanks again for your patience during this process! I hope we are getting close!
> 
> - Libby

**Comment by Jegelewicz** [comment]
> I am trying to find a point where I can stop other things and start on this - today, I hope... The 31st shouldn't be a problem, at least not one originating on my end!
> 
> -D

**Comment by Jegelewicz** [comment]
Dusty:

First question: What collection are these going into?

> There are two collections in Arctos
> UAM@ARCTOS> select guid_prefix from collection where guid_prefix like 'UMZM%';
> GUID_PREFIX
> UMZM:Bird
> UMZM:Mamm
> and I don't see anything obvious that would put these records into one of them. I tried CLASS without much luck...
> UAM@ARCTOS> select distinct CLASS from TEMP_UMZM_MAMM;
> CLASS
> Mammalia
> Chromadorea
> North america
> Actinopterygii
> Aves

Libby:

> “Class” should designate Aves or Mammalia to designate UMZM:Bird or UMZM:Mamm, respectively. Anything else is either a one-off or a mistake. Perhaps the easiest way to handle this problem now is to just pull out any item that says anything other than Mammalia or Aves. Alternatively, I can make corrections in the original database which will take more time, but I’ll try to make it a priority.  If I make corrections in the original database, does David need to process it again before it goes to you? I can try to have it done by this afternoon if that will help.

Dusty:

> I have a fair bit invested in cleanup at this point. Starting over would be copy/paste, but it would still be a few hours of it. I'd much prefer to correct what I have if that's possible.
> I've attached the results of...
> create table TEMP_UMZM_AMBIGUOUSCOLN as select * from TEMP_UMZM_MAMM where class not in ('Aves','Mammalia');
> There are only 14 so should be quick.
> (I'm sort of stuck in the middle of transforming this to the Arctos bulkloader format, so the columns will be weird - hopefully they make sense anyway!)
> I need back only catalognumber and class (with Mammalia/Aves as values) - feel free to delete the rest or I will or whatever.

Libby:

> Attached is the CVS in which I’ve corrected the items without the correct class. I also updated the scientific name to help with ambiguity for all but UMZM 7975, UMZM 13418 and UMZM 14222.
> The only one I was not able to designate as Aves or Mammalia is UMZM 3517 which is actually a parasite that was saved with a mammal and cataloged separately. Since it is the only item like this, I am happy to have it removed from the Arctos load.
> Let me know if anything is unclear.
> - Libby

Dusty:

> Blargh! Thanks, but I missed a few with NULL class. Attached.
> I went ahead and deleted the parasite - shall we start a parasite collection just for it?

**Comment by Jegelewicz** [comment]
Dusty:

> Next up: geography. There were a bunch of things with commas, I did this...
> update TEMP_UMZM_MAMM set locality_remarks='county given as ' || county where  county like '%,%';
> update TEMP_UMZM_MAMM set locality_remarks='state/province given as ' || STATEPROVINCE where  STATEPROVINCE like '%,%';
> and ran everything through my widget. Please review - higher_geog will go in to Arctos and should accurately (in conjunction with the remark from ^^ up there) represent the original components. Arctos geography data are available at https://arctos.database.museum/geography.cfm

Libby:

> For Geography, I believe the errors you are referring to are items that were collected on county or state borders; the original locality data specifies a border between two localities. What is the best way to put this kind of data into Arctos? As long as the data is in the verbatim_locality, any solution is fine with me.
> 
> Let me know if you plan to pull out oddities – if so, we should keep a running list of those catalog numbers so I know they aren’t going to be on Arctos. If I should fix these issues right now in the original database, does it make most sense for you to identify more problems before I resubmit it to you or David?
> 
> Thanks!
> Libby

Dusty:

> Arctos will not deal with ambiguity in authorities. I've mapped the ambiguous things to the "next biggest" component - the singular known entity. The original data are retained, and there are more options once things get into Arctos (eg, add a second locality).
> 
> FWIW, this is very common but usually not recorded. Locality is X, the point is in X so the checks are happy, but X is some weird shape and 99% of the error is hanging off into Y. Maybe someday we'll have everything georeferenced and better spatial tools....
> 
> I won't pull anything out. We can go there if there's something that you don't have time to clean or whatever, but that'll be your decision.
> 
> Here's the rough plan:
> - get everything mapped to the bulkloader format
> - get everything mapped to a collection
> - get confirmation on geography (it's easiest to clean before the bulkloader, while I still have the components)
> - push to the Arctos pre-bulkloader, from where we'll clean everything else up
> - load to Arctos

Libby:

> Just to follow up – your correction to change %,% to || fits the original locality data well for those items collected on the border. That should solve the issue, right?

Dusty:

> Yes, I think so.
> state=bla, county=x,y
> will go in as
> state=bla
> county=NULL
> locality_remarks="county given as x,y"
> 
> You will NOT see the remark in the geography file I sent - it's just the geography proper. You WILL see it when I send the full data a bit later.

**Comment by Jegelewicz** [comment]
Dusty

> Libby, I ran out of convenient space for attributes so I pulled out "lifestage" in the Attribute bulkloader format. It'll need loaded after the specimens are in; hopefully I won't forget, but it's attached just in case.
> 
> Ideally it would be cleaned up and changed into a more specific attributes - "adt" to age class (a categorical attribute - http://arctos.database.museum/info/ctDocumentation.cfm?table=CTAGE_CLASS) and "3.5 yrs" to numeric age (a number-plus-units attribute) and "imm?" to age (a free-text attribute) and etc. (I think some of those are only available for birds so it may not be quite that simple.) If time prohibits that we can find a home for them as they are.
> 
> I think I'm ready for the pre-bulkloader once I hear back regarding higher geography.
> 
> Thx-D

**Comment by Jegelewicz** [comment]
Dusty

> And by "couple hours" I apparently meant "few minutes" - I guess it's a slow morning and we had some extra processors hanging around. You should find several files attached.
> 
> There's some documentation at http://handbook.arctosdb.org/documentation/pre-bulkloader.html. PLEASE let me know if anything at all doesn't make any sense and I'll update the documentation.
> 
> Let me know if you can't do what needs done with a simple replace/lookup table. Some of these I think we'll need to add at least a whatever_this_thing_is_remarks or similar and repatriate it manually.
> 
> Looks like a bunch of attributes (eg ~a dozen ear length for birds) came to me as "0" which presumably means "we have no data" - I'll clean those up and may have more in a bit.
> 
> Accessions need to exist before specimens can load. Do you have more data to load with those, or would you like me to create as-blank-as-possible placeholders for these numbers, or ??

**Comment by Jegelewicz** [comment]
Libby:

> Hi Dusty,
> 
> Thanks for the files – my turnaround time won’t be quite as fast as yours, but I’ll try!
> 
> Quick question – can I correct some of the agent names for Arctos and leave others to be imported as “verbatim collector”? Or for the bulk load, will it be an all or nothing decision? The prebulkloader agent csv you sent me includes over 2000 names. I can quickly address most of them into correct Agents, but quite a few need more time or can’t be fixed with my current info.
> 
> Thanks for the advice. If it is all or nothing, we might have to do verbatim collector for everything in order to keep this process moving forward…

Dusty:

> I can do that, just make the intent somehow obvious - leave shouldbe NULL is probably easiest. Or it's easy to pull from verbatim collector later, if want to stash what you have until there's more time to deal with it.

**Comment by dustymc** [comment]
Data are http://arctos.database.museum/SpecimenResults.cfm?guid_prefix=UMZM%3ABird%2CUMZM%3AMamm
