### ISSUE TITLE
Chicago Academy of Sciences

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#12]
Ornithology data being published on the IPT is outdated - need to change the publishing source to Arctos (same as mammal and egg specimens).

**Comment by ccicero** [comment]
Also need to add CHAS Fish Collection to IPT.

**Comment by tucotuco** [comment]
Updated VertNet tasks (https://github.com/VertNet/Tasks/issues/198) to get this in the queue.

**Comment by ccicero** [comment]
Need eml file for CHAS fish.

**Comment by ccicero** [comment]
CHAS Ornithology (Arctos) published to VertNet IPT 2017-10-31.

**Comment by ccicero** [comment]
Erica created three additional eml files for:

CHAS:Ento
CHAS:Inv
CHAS:Herb

Data being added to Arctos but resources ready to publish to VertNet IPT.

**Comment by ccicero** [comment]
CHAS:Ento, CHAS:Inv, and CHAS:Herb published to VertNet IPT 2017-11-01.
