### ISSUE TITLE
UNR Billing

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#126]
Send billing information to Arctos Treasurer and submit initial invoice.

**Comment by Jegelewicz** [comment]
Invoice information added to the Rauthiflor Google Sheet. Email sent to John instructing to invoice UNR.

> John,
> 
> Please send University of Nevada, Reno their initial bill. It is marked as "send" in the Google sheet.
> 
> Thanks!

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by tucotuco** [comment]
Invoice RF0067 sent via PayPal to allow for payment by credit card.

**Comment by Jegelewicz** [comment]
Paid
