### ISSUE TITLE
UWBM MOU Steering Committee Review

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#128]
Draft MOU submitted for Steering Committee approval or modification

**Comment by Jegelewicz** [comment]
Derek Sikes:

> I'm traveling with minimal email access. Thanks for your patience.

**Comment by Jegelewicz** [comment]
Dawn Roberts

> Looks good to me Teresa. 
> 
> Dawn

**Comment by Jegelewicz** [comment]
Chris Witt

> I also think the Burke MOU looks good — too bad the bird collection there is not part of it — I will do what I can to peer pressure them.
> 
> Chris W

**Comment by jrdemboski** [comment]
This MOU looks good to me.

Teresa, once again, thanks for putting it together

John

**Comment by Jegelewicz** [comment]
MOU sent to Adam Leache and Sharlene Santana for signature.

> Adam and Sharlene,
> 
> I have created a PDF of the Arcots MOU that is ready for signature and placed it in Dropbox. Adam has already signed the document. Electronic signatures are fine. Once Sharlene has signed, please place the signed copy in the Dropbox or email it to me and I will forward it to John Demboski for his signature. After all signatures are complete, I will send you a final copy and your invoices will follow.
> 
> Thank you!
