### ISSUE TITLE
ACBC - Arkansas State Announce New Arctos Member

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#135]
[Arctos Communications Manager](arctos.communications@gmail.com) to announce new collection on the [Arctos Collection Trends](https://arctosdb.org/category/collections/) Page and in the next Arctos newsletter

**Comment by Jegelewicz** [comment]
From Arkansas MOU:

> The Arkansas State University – Jonesboro’s Arkansas Center for Biodiversity Collections houses specimens from the Arkansas State University Herbarium (STAR) and the Arkansas State University Museum of Zoology (ASUMZ). While ASUMZ and STAR will retain their official status with registered organizations, the ACBC will foster a unified and collaborative setting for education, research, and outreach on a regional scale.
> Arkansas State University – Jonesboro desires to participate in the Arctos Consortium and to receive services from Arctos as described in this MOU for the following collections: Herbarium, Aquatic Macroinvertebrates, Mussels, Insects, Fishes, Amphibians and Reptiles, Birds, and Mammals.

**Comment by campmlc** [comment]
Call with Travis Marsico and Diana Soteropoulos (Herbarium data manager) to submit new online collections request form and discuss setup of new portal.  Issue is whether to keep existing herbarium records under "STAR" portal and vertebrate records under "ASUMZ" portal. Both are now subsumed under Arkansas Center for Biodiversity Collections (ACBDC). The Star acronym is on barcodes affixed to herbarium records, and this is what they want cited. But the format is "STAR_000001". Possible suggestion to use ACBC as institution, Herb, Mamm, Fish etc as collections, and add STAR and ASUMZ numbers as other IDs. Thoughts? 
Also sent welcome email:
https://drive.google.com/file/d/1poLg-4ObBjsW5pmaOd8tUIvHlBOtIG54/view
[1_Welcome to Arctos letter.pdf](https://github.com/ArctosDB/new-collections/files/2288846/1_Welcome.to.Arctos.letter.pdf)

**Comment by campmlc** [comment]
From Diana at ACBC:

Hi, Mariel,

Thank you for talking us through our first steps as members of the Arctos community. Please find a mock up of how we want the Arkansas State University portal to appear on Arctos. It is based on the University of Alaska Museum portal.

We would like the entire collection to have the acronym ACBC, to reflect the unification of all the natural history collections at Arkansas State University through the Arkansas Center for Biodiversity Collections. For the first box under our portal name, we want to explain what the ACBC is, then have explanatory boxes for our plant collections (under STAR) and animal collections (under ASUMZ).

Next, each collection will appear with a description of the holdings, e.g., Plant specimens (STAR) (ACBC:Herb), etc.

We have requested each curator provide a written description of their collections to include on the portal. Please let us know if this format will work and if there is any additional information you need from us at this time.

I will be sending a spreadsheet of herbarium databased records later this evening.

Best,
Diana
[Arkansas State University portal mock up.docx](https://github.com/ArctosDB/new-collections/files/2288849/Arkansas.State.University.portal.mock.up.docx)
@lkvoong

**Comment by campmlc** [comment]
Close issue. Redirect to #90

**Comment by Jegelewicz** [comment]
No announcements have been made for ACBC.

**Comment by KyndallH** [comment]
07 January 2019: Newsletter
