### ISSUE TITLE
Arctos is down?

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/new-collections#14]
Getting this message:

Service Temporarily Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

**Comment by dustymc** [comment]
Please use https://arctosdb.org/join-arctos/contacts-support/ to report outages.

@mkoo @ccicero are ya'll monitoring arctos.database [at] gmail.com? That should probably be removed, I think anyone watching that will be aware that something is going on. You can add my dusytmc email if you want - it goes to my phone. And "Send an email to one or more below" should probably be "Send an email to ALL below".

**Comment by campmlc** [comment]
This is not an obvious or easy to remember place to go to in case of
outages.

On Aug 15, 2017 12:39 PM, "dustymc" <notifications@github.com> wrote:

Please use https://arctosdb.org/join-arctos/contacts-support/ to report
outages.

@mkoo <https://github.com/mkoo> @ccicero <https://github.com/ccicero> are
ya'll monitoring arctos.database [at] gmail.com? That should probably be
removed, I think anyone watching that will be aware that something is going
on. You can add my dusytmc email if you want - it goes to my phone. And
"Send an email to one or more below" should probably be "Send an email to
ALL below".

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ArctosDB/new-collections/issues/14#issuecomment-322551904>,
or mute the thread
