### ISSUE TITLE
UNE - Forward questionnaire to [Arctos Working Group](arctos-working-group@googlegroups.com) and request volunteers for collection mentor.

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#149]
AWG member can volunteer to act as primary contact, especially if they have similar collections or specific knowledge about a collection; can serve as ‘in kind support’ for collections to help offset costs

**Comment by Jegelewicz** [comment]
Link to above posted to [AWG Google Group](https://groups.google.com/forum/?hl=en#!topic/arctos-working-group/Nll8SYJstJ4)

**Comment by AJLinn** [comment]
I'd be happy to consult on their cultural collections. There are a lot of similar issues between the US and Australia regarding intellectual property and consulting with local Indigenous communities. If their existing cultural collections are in PastPerfect, they should be able to export that content pretty easily. In general, sounds like they're going to need quite a bit of support.

**Comment by dustymc** [comment]
This doesn't seem technically difficult. Their existing digital data can go through the normal channels, and the data they haven't digitized can go through the specimen bulkloader (and extensions). They can write to the bulkloader using the Arctos data entry interface or anything else that'll export CSV. Building custom forms might make some sense if the very minimal example data which were shared are typical. Eg it might make sense to capture data from images if they're scanning anyway.
