### ISSUE TITLE
OWU - MOU finalized and signed

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#154]
Signed MOU: saved to Arctos Shared/Institutional MOUs in Google Docs

**Comment by Jegelewicz** [comment]
Modified to add Chris Witt as Arctos rep.

> Chris,
> 
> OWU is prepared to sign this MOU. As soon as you give me the OK, I will convert to a PDF and send to them for signature. After they sign I will send to you for signature.
> 
> Thank you!
> 
> Teresa

**Comment by Jegelewicz** [comment]
PDF for signature sent to OWU

**Comment by lmtabak** [comment]
Signed PDF added to DropBox folder.

**Comment by Jegelewicz** [comment]
Sent to Chris for signature.

**Comment by Jegelewicz** [comment]
Final signed by both parties uploaded to Google Drive.
