### ISSUE TITLE
UCSC - Collection Portal Request

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#159]
Institution contact requests collection portal creation. Please use the form at [Reports/CollectionCreationRequest](http://arctos.database.museum/new_collection.cfm)

**Comment by Jegelewicz** [comment]
> Hi Teresa,
> 
> Thanks for all the info! Yes, I agree that in order to keep our collections consistent with the existing herbarium (also a part of the Norris Center!) that we use UCSC as our GUID. UCSC:Herp, UCSC:Fish, UCSC:Mamm and UCSC:Bird are all great for us. 
> 
> Looking forward to the forms to start creating our collections!
> 
> Thanks again,

Alex

**Comment by Jegelewicz** [comment]
Collections precreated. Awaiting information from UCSC.

**Comment by Jegelewicz** [comment]
> Alex,
> 
> I have sent your MOU to Chris Witt for signature and I have also pre-created your collections in Arctos. If you visit this page and scroll down past your initial questionnaire answers, you will see each of the four collections with places to complete the information I referenced in the attached email.  Once you have these forms complete, I can instruct the Database Manager to set up your collection portals. Let me know if you have any questions or issues as you complete the information. You can save and return to the forms so you don't have to complete everything at once.
> 
> I will send you a copy of the MOU once Chris has signed it.
> 
> Adios,
> 

Teresa J. Mayfield
Arctos Treasurer

**Comment by Jegelewicz** [comment]
> Alex,
> 
> I looked through the forms and before I set the process in motion to create the collections I want to make sure that you want your catalog numbers to be in the "Prefix-integer-suffix" format. I will warn you now that using any catalog number other than "integer" can make searches, reports, and sorting more difficult. The choice is definitely up to you (or perhaps has been made for you by those who came before you...), but if you can, I would recommend using integer catalog numbers.
> 
> Also, for your license, you selected "Arctos Data Ownership and Use" for all except birds, for which you selected "MVZ Terms of Use". Just wanted to make sure that was your intent and that you didn't want the same license for all of the collections.
> 
> Finally, I added the web addresses for the individual collections to the Collections URL, except for Amphibians and Reptiles as there are two separate pages for them on your site, so for that, I just used the main collections web page.
> 
> Make one more review and consider my comments above. You may want to chat with Carla as well. Once you are satisfied that everything is as you want it to be, just let me know and I can start the process of creating the collections in Arctos.
> 
> Thanks!

Teresa J. Mayfield
Arctos Treasurer

**Comment by Jegelewicz** [comment]
Yes from AWG Meeting notes 2019_01

Changed status to "approve to create collections" in Arctos.

**Comment by lkvoong** [comment]
Collections and Multi-collection Institutional Portal created:

http://arctos.database.museum/ucsc_bird
http://arctos.database.museum/ucsc_fish
http://arctos.database.museum/ucsc_herp
http://arctos.database.museum/ucsc_mamm
http://arctos.database.museum/ucsc_all

I granted access to 4 collections to the institutional mentor, Carla (ccicero), but I couldn't find an operator account/login for Alex Krohn.

**Comment by Jegelewicz** [comment]
Thank you!

**Comment by Jegelewicz** [comment]
> Authenticated!
> 
> Thanks, Carla. Looking forward to chatting about this on Wednesday.

-Alex

On Thu, Feb 7, 2019 at 11:33 PM Carla Cicero <ccicero@berkeley.edu> wrote:

    Hi Alex - I updated your agent information (address, email, title, etc.) in Arctos and invited you as an operator. You will need to authenticate your account by going to your profile (My Stuff ---> Profile) and retyping your password. If it's acceptable, you'll get an Authenticate button. If it's not acceptable, you'll need to change it. Passwords should have at least 8 characters and include at least one number, capital letter, and symbol like $ or !

    Once you've validated your account, I can assign you roles. We can go over this when we meet on Wednesday to talk about the tissues.

    Here is some documentation that should be helpful in creating your Arctos users.

    FYI, I have an Arctos Steering Committee meeting on Wed 2:30-3:30, so we can meet after MVZ lunch until 2:30, and pick things up again after my meeting if needed. 

    Best,
    Carla
