### ISSUE TITLE
UCSC - Announce New Arctos Member

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#166]
[Arctos Communications Manager](arctos.communications@gmail.com) to announce new collection on the [Arctos Collection Trends](https://arctosdb.org/category/collections/) Page and in the next Arctos newsletter

**Comment by Jegelewicz** [comment]
@KyndallH Contact information - Alex Krohn arkrohn@ucsc.edu

**Comment by KyndallH** [comment]
July 2019 newsletter.
