### ISSUE TITLE
MSB Herp Collection

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#17]
Needs to be added to VertNet IPT.

**Comment by jtgiermakowski** [comment]
created eml.xml file in Dropbox/ArctosForVertNet/add/msb_herp

**Comment by dbloom** [comment]
Published.  https://www.gbif.org/dataset/fb639e31-52eb-4998-afb1-984ee12aca0f

**Comment by jtgiermakowski** [comment]
Sweet! thank you.

**Comment by jtgiermakowski** [comment]
Works like a charm, both on Vertnet and GBIF portals, closing.
