### ISSUE TITLE
OWU - Announce New Arctos Member

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#171]
[Arctos Communications Manager](arctos.communications@gmail.com) to announce new collection on the [Arctos Collection Trends](https://arctosdb.org/category/collections/) Page and in the next Arctos newsletter

**Comment by Jegelewicz** [comment]
@KyndallH OWU has records in Arctos! Have we already announced them?  If not, contact is Lisa Tabak lmtabak@owu.edu

**Comment by Jegelewicz** [comment]
@KyndallH have we done this?

**Comment by KyndallH** [comment]
Done in the April newsletter.
