### ISSUE TITLE
NMMNHS Announce New Arctos Member

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#174]
[Arctos Communications Manager](arctos.communications@gmail.com) to announce new collection on the [Arctos Collection Trends](https://arctosdb.org/category/collections/) Page and in the next Arctos newsletter

**Comment by KyndallH** [comment]
Do they have specimens in Arctos already? Tried to find them but didn't see it. Once they do, I'll do a tweet and post it to the webpage. I'll put them down for the next newsletter collection highlight.

**Comment by KyndallH** [comment]
July 2019 newsletter.
