### ISSUE TITLE
ASNHC - Angelo State Announce New Arctos Member

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#177]
[Arctos Communications Manager](arctos.communications@gmail.com) to announce new collection on the [Arctos Collection Trends](https://arctosdb.org/category/collections/) Page and in the next Arctos newsletter

**Comment by Jegelewicz** [comment]
MOU signed and first bill being prepared. They already have some data in Arctos.

From their MOU:

> The Angelo State University Biology Department maintains the Angelo State Natural History Collections, which contains nearly 95,000 specimens of all types of living organisms. The collections are preserved, documented and curated assemblages that are important to a wide array of human activities.

Contact info: Dianna Krejsa - Dianna.Krejsa@angelo.edu

**Comment by Jegelewicz** [comment]
@KyndallH have we announced them?

**Comment by KyndallH** [comment]
April 2019 newsletter.
