### ISSUE TITLE
Angelo State 

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/new-collections#18]
Request for fee reduction received, approved by ASC; need to formally contact to indicate approval of request; new collections manager recently hired with Arctos background from MSB

**Comment by campmlc** [comment]
[Angelo State_ New submission_ Arctos Participation Initial Questionnaire.pdf](https://github.com/ArctosDB/new-collections/files/1794043/Angelo.State_.New.submission_.Arctos.Participation.Initial.Questionnaire.pdf)

**Comment by campmlc** [comment]
[Angelo State fee reduction application.pdf](https://github.com/ArctosDB/new-collections/files/1794053/Angelo.State.fee.reduction.application.pdf)
[Fee reduction approval Angelo State Oct 2017.pdf](https://github.com/ArctosDB/new-collections/files/1794062/Fee.reduction.approval.Angelo.State.Oct.2017.pdf)

**Comment by Jegelewicz** [comment]
Draft MOU and Modification created, needs review. https://drive.google.com/drive/folders/1fRa76v6bFJLPk25wpTKRfY9MJ0yMx5We?usp=sharing
@campmlc @jrdemboski @ccicero

**Comment by Jegelewicz** [comment]
March 19, 2018
MOU draft sent to Dianna Krejsa <dianna.krejsa@angelo.edu>

**Comment by Jegelewicz** [comment]
Revised [MOU Modification](https://drive.google.com/open?id=1CS-WjzxBpO8Utq_JnGOQSxldaM1qDghD) sent to Dianna.

**Comment by Jegelewicz** [comment]
We Need to respond to questions regarding the Angelo State MOU.  Please help where you are assigned.

> -The fees listed for the next five years are "flat" (no additional $0.02/specimen), correct? But they are before the 5% administration fee?
I would answer yes to this, but I'm guessing that would not help our cause, so I suggest we say the flat fee includes the admin fee.  Please let me know if you have a different response @campmlc @jrdemboski @ccicero 

> -As far as backups, Arctos has several servers working as hard-backups in a couple places nationwide I think, how many and where are they again?
All data are stored and backed up at TACC in Austin, Texas.
@dustymc anything else?

> -Can we host our own server backup of our data here at ASU?
No, but you can get a flat file. @dustymc  comments?

> -How does storage of images work? They are hosted at TACC I believe, but will there be a cap on space for Arctos or storage fee for institution? We have approximately 57000 imaged plants, and of course more to follow.
All images are hosted at TACC and currently there is no cap, nor do we expect any.

> -Are the taxon trees static to be compatible Arctos-wide, or is our instance of Arctos editable for taxon tree? I am mostly asking for the plants, we were dealt a bad taxon tree to conform to from Specify many years ago (is my understanding), genera listings were under family level hierarchies, batch editing was impossible, and other persisting issues. Can you give us some insight on how the trees work?
Taxa are flexible and may be entered by collections as needed although we are all encouraged to manage the taxa responsibly. The Arctos Working Group settles issues related to taxonomy and all collections are encouraged to participate. @dustymc @campmlc @ccicero any comments?

> Finally, can we do a trial upload of 100 vertebrate specimens and 100 herbarium mounts (with images) to get an idea of migration process? Can we upload to the demo view perhaps, so an account doesn't have to be opened for us? 
Do we have them use test or just set up their portal for this? Do we let them set up all the vertebrate collections they need or ask them to limit the test to one (Mamm, Herp, etc.)? @campmlc @ccicero @dustymc

**Comment by campmlc** [comment]
How much effort does it take to set up a new collection portal? One idea would be to provide a portal and a certain number of records free. That way collections could test the migration pathway and the interface.


This would be similar to what Specify did as a recruitment tool  - give away the software, get as many collections as possible using it, and then gradually work up to charging them.


Would this be an option for new collections,  rather than having them use test?


Mariel Campbell

Collection Manager, Division of Genomic Resources
Museum of Southwestern  Biology

Shipping Address:
Museum of Southwestern Biology
Division of Genomic Resources
University of New Mexico
CERIA Bldg 83, Room 204
Albuquerque, NM 87131

(505) 277-7808 office
email: campmlc@unm.edu




________________________________

**Comment by Jegelewicz** [comment]
@dustymc Can we set up Mamm and Herb collections for Angelo State? As per above, we are going to let them get practice uploading data. They are registered in GRBio as [ASNHC ](http://grbio.org/institution/angelo-state-natural-history-collection).
