### ISSUE TITLE
BYU Draft MOU

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#182]
Work with new collection to complete Draft MOU, answer any questions about migration, Arctos operating procedures, and costs; (download sample template include collection contact info).

Place draft in Dropbox, share with new collection contact, AWG Chair, AWG Vice Chair, and any collection Mentors

Send email to New collection Contact and copy the above.

**Comment by Jegelewicz** [comment]
Draft created and shared in dropbox with @acdoll for review.

**Comment by acdoll** [comment]
On it.

**Comment by Jegelewicz** [comment]
Made changes based on comments and sharing with BYU.

**Comment by Jegelewicz** [comment]
Shared draft in Dropbox

> Alison,
> 
> The BYU/Arctos MOU draft is in this shared Dropbox folder. Please review and edit as necessary.
> 
> The BYU collections description was taken from your website, but you may edit that as you see fit. If you would like to be billed on a date other than the start of your fiscal year, let me know so that we can edit the MOU accordingly. Finally, if you will not be the person signing the MOU, please provide the contact info for the person who will in the contacts section.
> 
> Email arctos.treasurer@gmail.com if you have any questions.
> 
> Thanks!
> 

Teresa Mayfield-Meyer
Arctos Treasurer

**Comment by Jegelewicz** [comment]
> Teresa,
> 
> The MOU and payment has been approved.  I'm not sure why, but I was having trouble editing the document in dropbox, so I uploaded the edited version.  Let me know if this will work.  As soon as this is approved we can submit payment and we are ready to go.
> Thanks
> Alison
> 

Assistant Curator
Monte L Bean Natural History Museum
Brigham Young University

**Comment by Jegelewicz** [comment]
Sent to Steering Committee for review
