### ISSUE TITLE
BYU - MOU Steering Committee Review

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#184]
Draft MOU submitted for Steering Committee approval or modification

**Comment by Jegelewicz** [comment]
> Arctos Steering Committee Members,
> 
> I have attached the MOU for BYU. They are prepared to sign this document. Please review and let me know if you approve or if changes need to be made.
> 
> Thanks,
> 

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by Jegelewicz** [comment]
> I approve — it looks great, and will be great to have BYU on Arctos.


Chris W.

**Comment by DerekSikes** [comment]
Where is the draft? Is there a link?

**Comment by Jegelewicz** [comment]
Sent it via email as attachment.

**Comment by Jegelewicz** [comment]
> I see it now. I approve.


-Derek

**Comment by Jegelewicz** [comment]
> Looks good. I approve.

Dawn

**Comment by Jegelewicz** [comment]
> I approve

John Demboski

**Comment by Jegelewicz** [comment]
> I approve.

Michael Nachman
Director, Museum of Vertebrate Zoology

**Comment by Jegelewicz** [comment]
No response from @dbloom but sent to BYU for signature.
