### ISSUE TITLE
Naturalis Biodiversity Center Netherlands

### ISSUE THREAD

**Issue by campmlc** [ArctosDB/new-collections#19]
Name: Iris van Breda   4 October 2017
Email: iris.vanbreda@naturalis.nl 
Message: Dear Madam/Sir, My name is Iris van Breda and I work as an application manager at Naturalis Biodiversity Center in the Netherlands. We are currently investigating the possibility to switch to a different Collection Management System one of the options being considered is Arctos. A while ago we sent out a survey (https://tinyurl.com/survey-naturalis) to a range of Natural History Museums about their CMS. We received very positive feedback about your system. We have a couple of questions about Arctos that you can hopefully answer for us, we couldn't find it in your extensive documentation. 1. It's crucial that we do have direct access to the Oracle database, and have ownership over our data. Not only for queries but also to prevent vendor lock-in. Is this a practice you support? 2. We currently hold circa 10 million digital specimen records, can Arctos handle those numbers? Our data would triple the current number of records, we're not sure if Arctos is more geared towards smaller institutions/datasets. 3. Our institution is based in the Netherlands. From what I can tell, all current Arctos users are US based. Would that be a problem? e.g. I read somewhere that you index the database every night. That could possibly hinder our work, considering the time zones. Thank you for taking time out to answer my questions. With kind regards, Iris van Breda application manager Naturalis Biodiversity Center
Iris, 
The Arctos Steering Committee would welcome your application to join Arctos, and we would be happy to work with your institution to address any technical concerns that may arise.
 Regarding your initial questions:
1. Direct access to the Oracle database: Yes, with virtual private databases, the command line provides access to the Arctos front end.
   Each collection has control over how to license their data, see https://arctosdb.org/search-arctos/data-licensing-use/. You can supply your own license.
2. From a hardware perspective there shouldn’t be any problem handling the size of the database. We have plenty of spare capacity. 
3. We currently do not experience any extra load from data indexing, but if the increase in database size were to create problems we would certainly work with you to make any required adjustments.

The next step to move forward would be for you to fill out the initial questionnaire or an application to join at https://arctosdb.org/join-arctos/ . Please let us know if you have any additional questions. We can also put you in direct communication with our technical staff.

Thank you!

Mariel Campbell

Hi Mariel,

Thank you for your thorough reply. After talking with my manager, we realized I had overlooked something. Because we are a national research center we need to store our data in the Netherlands, or at least within the European Union. We are not allowed to store (such crucial) data overseas. 
This is probably too much to ask, but would it be possible to use Arctos, while we store the data, within our own datacenter?

Iris,

Yes, this is possible -  in fact it is a model we are working on developing with other institutions. You could host your data on your own servers using a separate instance of Arctos, or host a combined instance with the rest of the community.  Depending on how this was done, providing your own servers and programmers could potentially go towards cost reduction as in kind support that would benefit the entire Arctos community. We would be happy to discuss this further.
Mariel 

Dear Iris,  13 November 2017

I am following up on your request and wanted to make sure that Mariel had been able to answer all your questions. We would very much like to work with you to develop your own instance of Arctos in the Netherlands. As you may know, the Museum of Comparative Zoology at Harvard runs a separate instance of Arctos now (they have a bit over 2M specimens) and we are quite keen to think about setting up an international instance Please feel free to send any questions you might have.

sincerely,
Joseph Cook
Chair, Arctos Steering Committee
President, Natural Science Collections Alliance
Member, BCoN and VertNet Steering Committees

**Comment by Jegelewicz** [comment]
[Pre call email and response](https://docs.google.com/document/d/1BUHddLBiO4LDAgzdCKR8es1mk5r4R-tJOzApxa67iKs/edit?usp=sharing)

includes Notes from call on March 21, 2018
Attendees: Naturalis [Iris van Breda, Judith Slaa], Arctos [Mariel Campbell, Joe Cook, Tom Giermakowski, Teresa Mayfield]
