### ISSUE TITLE
University of Texas - El Paso

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#2]
[Univ_Texas_El_Paso_20151110.pdf](https://github.com/ArctosDB/jotform/files/153690/Univ_Texas_El_Paso_20151110.pdf)

**Comment by ccicero** [comment]
Need to register collections with GRBIO: http://grbio.org/institution/university-texas-el-paso-biodiversity-collections

Once collections are registered at GRBIO, then they need to be created in Arctos.

Mammals
Birds
Amphibians
Reptiles
Fishes
Insects
Invertebrates
Myrmecology
Herbarium

**Questions/comments:**

1. Tissues are treated as part of a specimen and not a separate collection.
2. Are amphibians and reptiles two collections or one herpetology collection?
3. Are Insects, Invertebrates, and Myrmecology all separate collections?

**Comment by ccicero** [comment]
Signed MOU sent to Eli Greenbaum at UTEP 19 July 2016.

**Comment by ccicero** [comment]
Herps, fish, mammals, plants, earth sciences in Arctos 19 Dec 2016. 
Fish, mammals, plants in VertNet IPT. Fish and mammals published to VN portal 19 Dec 2016.

**Comment by ccicero** [comment]
Per Teresa Mayfield: Earth Science and Herps are already on VertNet as static collections.  Once I have them completely migrated to Arctos, we will switch them over.

**Comment by Jegelewicz** [comment]
As of today (August 28, 2017) only our Herps should remain in VertNet as a static collection and the following should be published from Arctos:

Specimen records
UTEP:Fish
UTEP:Ento
UTEP:Bird
UTEP:ES
UTEP:Inv
UTEP:Mamm
UTEP:Herb
UTEP:Zoo

Observation records
UTEPObs:Ento
UTEPObs:Herp

**Comment by ccicero** [comment]
According to the VertNet task list, metadata for the following collections were sent to Teresa @Jegelewicz for review in Oct 2016:

UTEP:Inv (https://github.com/VertNet/Tasks/issues/409)
UTEP:Ento (https://github.com/VertNet/Tasks/issues/408)
UTEP:ES (https://github.com/VertNet/Tasks/issues/406)
UTEP:Bird (https://github.com/VertNet/Tasks/issues/405)

The following collections are already connecting to the [VertNet IPT](http://ipt.vertnet.org) via Arctos:
UTEP:Fish (https://github.com/VertNet/Tasks/issues/407)
UTEP:Mamm (https://github.com/VertNet/Tasks/issues/410)
UTEP:Herb (https://github.com/VertNet/Tasks/issues/411)

Additional new collections added to VertNet Task List:
UTEP:Zoo (https://github.com/VertNet/Tasks/issues/540)
UTEPObs:Ento (https://github.com/VertNet/Tasks/issues/541)
UTEPObs:Herp (https://github.com/VertNet/Tasks/issues/542)

**Comment by Jegelewicz** [comment]
According to the VertNet task list, metadata for the following collections were sent to Teresa @Jegelewicz for review in Oct 2016:

UTEP:Inv (VertNet/Tasks#409)
UTEP:Ento (VertNet/Tasks#408)
UTEP:ES (VertNet/Tasks#406)
UTEP:Bird (VertNet/Tasks#405)

I have reviewed and updated these.

**Comment by ccicero** [comment]
UTEP collections updated and published to VertNet IPT 2017-09-15 and 2017-10-07, and new or updated records harvested/indexed to portal 2017-10-19. Only UTEP Vertebrates remains as a non-Arctos collection on VertNet IPT (includes only herps). Still need to publish:

UTEP:Zoo (VertNet/Tasks#540)
UTEPObs:Ento (VertNet/Tasks#541)
UTEPObs:Herp (VertNet/Tasks#542)

Also, what about UTEP:HerpOS? Not on VertNet task list. Is this ready to publish?

Need eml files.

**Comment by Jegelewicz** [comment]
Thanks! The UTEP:HerpOS data is included in UTEP Vertebrates. We will publish UTEP:HerpOS when we publish UTEP:Herp.

**Comment by ccicero** [comment]
Teresa - Do you want to make the eml metadata files for UTEP:Zoo, UTEPObs:Ento, and UTEPObs:Herp ? I created folders for each of those in the ArctosForVertNet dropbox folder. The easiest way is to download an existing eml file from one of your resources on the VertNet IPT, then change the relevant information including resource name, description, taxonomic and geographic and temporal coverage, etc. Let me know if you need any help with this. @Jegelewicz

**Comment by Jegelewicz** [comment]
Carla,
I’m out of town for the week but will check into it next week and let you know if I need assistance.
Thanks!

**Comment by Jegelewicz** [comment]
@ccicero I don't believe that the ArctosForVertNet dropbox folder has been shared with me. Also, I am unsure how to "download" and EML file from one of our other collections. I can open one from the VertNet site, but I don't want to edit it for fear of changing the file for the collection I am looking at. Do I copy and paste into an editor such as Notebook and save the file?

**Comment by jtgiermakowski** [comment]
Hi Teresa! that's exactly what I did. I used Notepad++ to edit the file (it has a very nice XML extension) and save it in the Dropbox. you can copy the EML file from msb_herp (really, anyone of those is fine).

**Comment by Jegelewicz** [comment]
Thanks, but I don't have access to the ArctosForVertNet dropbox folder! Who can share that with me?

**Comment by jtgiermakowski** [comment]
Here's a zipped version of msb_herp

[eml.zip](https://github.com/ArctosDB/new-collections/files/1480643/eml.zip)

**Comment by Jegelewicz** [comment]
@ccicero I made an attempt at the UTEP:Zoo eml file. Let me know if this will work. I used the UTEP:Bird file from VerNet which is now out of date. Do these files need to be updated every time there is a change in the collections? If so, all of UTEP's will need to be corrected.

[UTEP_Zoo.txt](https://github.com/ArctosDB/new-collections/files/1755534/UTEP_Zoo.txt)

**Comment by Jegelewicz** [comment]
@ccicero I do not have access to the ArctosForVertnet dropbox.

**Comment by dbloom** [comment]
I have the .zip.  Will let you know if there is more/different that is needed.

And, YES, if you have changes to make in the metadata for any collection, please let me know what those changes are, if they are few, or get me a new eml file, if they are many.

**Comment by Jegelewicz** [comment]
@dbloom Here is the eml file for UTEP:Ento. We are ready to start publishing this. Please let me know if you need anything else. 

[UTEP_Ento.zip](https://github.com/ArctosDB/new-collections/files/2172831/UTEP_Ento.zip)

**Comment by Jegelewicz** [comment]
@dustymc would it be possible to change the Collection Name for the UTEP:HerpOS collection? As the other herp collection is called "Amphibian and reptile specimens", I would like the HerpOS collection to be "Amphibian and reptile osteology specimens" for consistency. Thanks!!!

**Comment by Jegelewicz** [comment]
@dbloom 

Did you ever get the collection code from Dusty for the UTEP Entomology Collection? Vicky is ready to have it published to iDigBio/GBIF and it will also be scooped up by SCAN.

Let me know if you need anything else from me to get this done.

Thanks!

**Comment by dustymc** [comment]
@Jegelewicz  yea sure done.

>consistency

https://github.com/ArctosDB/arctos/issues/1662

**Comment by Jegelewicz** [comment]
@dbloom can you help me figure this out please?

From Neil Ford:

> Here is another apparent duplicate data set, this one from UTEP, I am copying UTEP people on this email.
> 
> Thanks,
> 
> Neil
> 
> aa08bb57-599d-4a9b-9f03-0db03e43d41d | 1 | UTEP Ento (Arctos) | https://www.gbif.org/dataset/aa08bb57-599d-4a9b-9f03-0db03e43d41d | The University of Texas  at El Paso Biodiversity Collections Entomology collection includes The  Mackay Laboratory of Myrmecology which is overseen by William P. Mackay  and has a mission to advance the understanding  of ants through research on their taxonomy, systematics and ecology as  well as a variety of other insects and arthropods. | 516 | University of Texas at El Paso Biodiversity Collections | https://www.gbif.org/publisher/52c8f620-1816-11da-9544-b8a03c50a862 | http://www.utep.edu
> -- | -- | -- | -- | -- | -- | -- | -- | --
> 297ecc07-da20-4ebf-9f41-4f80330b4b33 | 1 | UTEP Insects (Arctos) | https://www.gbif.org/dataset/297ecc07-da20-4ebf-9f41-4f80330b4b33 | University of Texas at El  Paso Biodiversity Collections Arthropod collections consist primarily  of ants from around the world collected by Professor William Mackay and  his students.  A variety of other insects  are included, primarily from student projects in the El Paso vicinity.
> 
>

**Comment by Jegelewicz** [comment]
> HI Andrea,
> 
> The Herpetology collections from UTEP have been republished as two separate Arctos resources.
> 
> UTEP Herpetology: https://www.gbif.org/dataset/395dfaad-8b0d-47e2-a2ea-bf8a3fd5c10c
> UTEP Herpetology Osteology: https://www.gbif.org/dataset/beddb937-47b8-48f6-8efb-e347383aa9b5
> 
> Please remove UTEP Vertebrates (https://www.gbif.org/dataset/bd2feca8-ec39-4480-9dad-e353ab6a506d), as this contained the last collection from UTEP that had not been moved into Arctos (Herps).
> 
> Many thanks
> dave
> 

David Bloom
VertNet Coordinator
