### ISSUE TITLE
BYU - Collection Portal Request

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#200]
Institution contact requests collection portal creation. Please use the form at [Reports/CollectionCreationRequest](http://arctos.database.museum/new_collection.cfm)

**Comment by Jegelewicz** [comment]
>Teresa,
>
> Here is the information you requested.  I think I have filled it out correctly, but let me know if I have misunderstood any requests.
> 
> Collection description:
> 
> The BYU herpetology collection houses over 40,000 fluid preserved specimens, including 36 types, and over 15,000 tissue samples.  The geographic focus of the collection is the Great Basin/Intermountain West, but there are also extensive collections from Latin America, Central Africa, and the Pacific. 
> Website:
> [Research Collections](https://mlbean.byu.edu/Research-Collections)
> 
> License:
> I am going to check with Duke on this, but I think we will just use the General Arctos Data ownership and Use document for now.
> 
> 
> Catalog number format:
> Integer
> 
> Loan Policy:
> [Policies and Loans](https://mlbean.byu.edu/Research-Collections/Policies-and-Loans)
> 
> Taxonomy source:
> I am a little fuzzy on what you are looking for here.  When I click on the table there are only three options, and Arctos is the only applicable choice.  Is that what you want here, or is ICZN an alternative option?
> 
> User account:
> My user name is alisonwhiting.  I asked Duke to set up an account and I will pass on that username when I get it. 
> 
> Thanks so much

Alison Whiting

**Comment by Jegelewicz** [comment]
> Alison,
> 
> Thanks! That was perfect!
> 
>     Taxonomy source:
>     I am a little fuzzy on what you are looking for here.  When I click on the table there are only three options, and Arctos is the only applicable choice.  Is that what you want here, or is ICZN an alternative option?
> 
> 
> The taxonomy source provides all of the classifications that are related to your specimen identifications. All of our vertebrate collections currently use the Arctos source. You do have the option of creating your own source from scratch, but I see no reason that you would want to do that.
> 
> You will receive an email from Arctos shortly inviting you to become an Arctos operator. If you don't get an email by tomorrow morning, check your SPAM folder. If you don't find it there, let me know and I will re-send.
> 
> Adios,

Teresa J. Mayfield-Meyer

**Comment by Jegelewicz** [comment]
Operator invitation sent.

**Comment by Jegelewicz** [comment]
Approved to Create Collection @lkvoong

**Comment by lkvoong** [comment]
BYU Herp collection created:

- Public Portal: https://arctos.database.museum/byu_herp
- Collection Access granted to:
-- Mariel (campmlc)
-- Teresa (jegelewicz)
-- Alison (alisonwhiting)
- FYI: The collection does not yet show up in the Portals page; it may take up to 24 hours to refresh.
- Please ask Alison to log in and update the collection profile, if necessary.

**Comment by campmlc** [comment]
Thanks, Lam!

**Comment by Jegelewicz** [comment]
Thank you!
