### ISSUE TITLE
BYU - GitHub and AWG membership

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#201]
Collection mentor to assist with Github registration if not already done; access to issues, documentation.

**Comment by Jegelewicz** [comment]
Alison is on GitHub

**Comment by Jegelewicz** [comment]
@AJLinn can you invite Alison to join the AWG? alison.whiting@yahoo.com

**Comment by AJLinn** [comment]
Did you already send the "Welcome to Arctos" document or is that what you're asking me to do?

**Comment by AJLinn** [comment]
2019-08-02: 
1:00 pm (Ak time) AWG google group invitation sent
1:14 pm Welcome to Arctos letter and email sent
