### ISSUE TITLE
BYU - Billing

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#204]
Send billing information to Arctos Treasurer and submit initial invoice.

**Comment by Jegelewicz** [comment]
> Alison,
> 
> I have attached a copy of the MOU signed by both parties. I am going to ask Rauthiflor to prepare an initial invoice for $105.00 so that we can start the process of getting them into your system. You will receive an invoice from Rauthiflor in the next week or so.
> 
> Let me know if you have any questions.
> 
> Thanks!
> 

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by Jegelewicz** [comment]
> John,
> 
> Please issue the initial invoice for BYU. I have set their invoice payment status to send in the google sheet.
> 
> Thanks!
> 

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by tucotuco** [comment]
Sent.

**Comment by Jegelewicz** [comment]
Paid.
