### ISSUE TITLE
BYU - Announce New Arctos Member

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#205]
[Arctos Communications Manager](arctos.communications@gmail.com) to announce new collection on the [Arctos Collection Trends](https://arctosdb.org/category/collections/) Page and in the next Arctos newsletter

**Comment by Jegelewicz** [comment]
@KyndallH please work with @byuherpetology to create the announcement. Thanks!

**Comment by KyndallH** [comment]
In Oct. newsletter and on the webpage.
