### ISSUE TITLE
JSNM - Notify Arctos Working Group

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#223]
Forward questionnaire to [Arctos Working Group](arctos-working-group@googlegroups.com) and request volunteers for collection mentor.

**Comment by Jegelewicz** [comment]
> Arctos Working Group:
> 
> [Jurica-Suchy Nature Museum at Benedictine University](https://www.ben.edu/museum/) is considering migrating into Arctos. Information about their collections and correspondence we have had with their collection manager can be found [here](https://github.com/ArctosDB/new-collections/issues/221). If you are interested in helping to mentor them through the process of joining Arctos and migrating their data, please comment on this GitHub issue.
> 
> Thanks in advance!

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by mbprondzinski** [comment]
This seems a manageable size, but do you think I am capable of "mentoring"?  I know nothing about cost, etc.

**Comment by campmlc** [comment]
Mentoring is primarily helping them with their data migration and helping
them get involved with the working group and github etc. Anyone who
volunteers as a mentor becomes a point of contact for the new collection.
You can always reach out to the community with any questions about how to
proceed.

**Comment by Jegelewicz** [comment]
@mbprondzinski they do have fossils, so you could probably be helpful there. Just want to make sure you feel you have the time to give!

**Comment by mbprondzinski** [comment]
I will accept the challenge!

**Comment by Jegelewicz** [comment]
@mbprondzinski and @Jegelewicz will be mentors.
