### ISSUE TITLE
LU - Collection Portal Request

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#225]
Institution contact requests collection portal creation. Please use the form at [Reports/CollectionCreationRequest](http://arctos.database.museum/new_collection.cfm)

**Comment by Jegelewicz** [comment]
> Jon,
> 
> Here is a final copy of the MOU signed by both parties. I will now ask Rauthiflor to issue your initial invoice for $105.00.
> 
> The next step is to request the creation of your portal. I need to make sure I know what your institution acronym will be. Have you and Michelle agreed on one yet?
> 
> Adios,
> 

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by Jegelewicz** [comment]
> Jon,
> Sorry! after sending my last message, I saw your reply about the institutional acronym. LINGU it is!
> In addition to your new user account, I have a couple of other items required for a new collection portal:
> 1. What license would you like to place on your collection data?2. We require every collection to provide a link to a loan policy. Can you place a loan policy on line and provide a link? I have used the LU home page as a plce holder for now.3. Do you have a webpage for your collection yet? We can provide a link to that as well.4. I have selected integer for your catalog number value. This will allow you to let Arctos assign numbers.
> If you have any questions, just let me or Michelle know. Once these items are resolved, I can request that your portal be created.
> Thanks!

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by Jegelewicz** [comment]
Awaiting license decision.

**Comment by Jegelewicz** [comment]
> Dear Teresa,
> 
> I am Itzue Caviedes-Solis, I am working with Jon Fong in the Lingan collection. I am contacting you regarding the information you requested to include our collection in Arctos. I included here the links for the collection and the loan policy. Our decision for the licensing is CC0 but we are not sure if it needs to be included in the website, the loan policy or if its just for your record. Do we need to include it somewhere?
> 
> Lingnan Collection Website
> https://lingnancollection.wixsite.com/naturalhistory
> 
> Policy Loan
> https://lingnancollection.wixsite.com/naturalhistory/loan-policy
> 
> Please let us know if you need anything else!
> Sincerely,

Itzue

**Comment by Jegelewicz** [comment]
> Itzue,
> 
> The license is recorded in Arctos. I do need one more thing before we can get the portal set up. I sent Jon an invitation to be come an Arctos Operator. I need him to follow the instructions in the email to authenticate so that I can make him the admin on the collection.
> 
> Thank you!
> 

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by Jegelewicz** [comment]
> Jon and Itzue,
> You are an authenticated operator. I will now instruct our DBA to set up your collection in Arctos. I'll let you know as soon as it it is up, then walk you through some initial steps to make sure everything appears as it should and that you both can start working with your collection.
> Adios,

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by Jegelewicz** [comment]
Approved to create collection.

**Comment by Jegelewicz** [comment]
@lkvoong Please create the LINGU:Herp collection. Thanks!

**Comment by mkoo** [comment]
Hi all, checking in with @lkvoong on collection creation; has this happened already? I dont see it.

I have registered the institution and Jon Fong as the contact for LINGU on GRSciColl. And will create the herp collection next but wanted to be able to add in their Arctos collection link. Please let us know the status.

**Comment by lkvoong** [comment]
@mkoo @Jegelewicz 

Sorry for the delay! I've been missing these messages; I've updated my email filter so hopefully, this won't happen again.

For the Lingnan University Herp collection, the guid prefix in the form, 'LINGU', is an invalid value.   The guid_prefix needs to follow the format X:Y where X references the Institution and Y references the collection. I think the only limitation so far is that dashes and colons are not allowed in X and Y, but you should check with Dusty for the rules.

Let me know what the new guid_prefix should be and I will proceed with making the collection.

**Comment by Jegelewicz** [comment]
Just updated that - apologies! Should be LINGU:Herp

**Comment by lkvoong** [comment]
I've created the Lingnan University Herp collection:

LINGU:Herp - http://arctos.database.museum/lingu_herp

It's not yet showing up on the Portals page (may take up to 24 hours to refresh), but the link to the public portal above is working.

Access was granted to: lingnancollection (Jon), mkoo (Michelle), and  jegelewicz (Teresa).

Please ask Jon to log in and update the collection profile, if necessary.

Thanks!

**Comment by mkoo** [comment]
Wonderful! thanks!
