### ISSUE TITLE
MSB Fish collection - ready for VertNet/GBIF

### ISSUE THREAD

**Issue by jtgiermakowski** [ArctosDB/new-collections#24]
Hi, 

I'm helping Lex to get MSB Fish connected to VertNet and GBIF. 
I created eml.xml file in Dropbox/ArctosForVertNet/add/msb_fish

MSB Fish are already in ARCTOS and the resources are ready to be published to VertNet IPT. 

¡Saludos!

**Comment by dbloom** [comment]
Published.
