### ISSUE TITLE
University of Antananarivo [via DMNS] Paleo

### ISSUE THREAD

**Issue by acdoll** [ArctosDB/new-collections#244]
Questionnaire completed by
David W. Krause
Arctos Username
dkrause
Job Title
Senior Curator of Vertebrate Paleontology
Email
David.Krause@dmns.org
Phone
631-942-7232
Status
administrative_approval_granted

Link
https://arctos.database.museum/new_collection.cfm?action=manage&id=A6FB2BEF4EB3307FD47AE0D85BB7A62A
Institution Acronym
UA
Institution
University of Antananarivo (UA)
How many total specimens across all collection(s) are you interested in migrating to Arctos?
<10,000
Are the data for all of those specimens in digital format?
yes
Which of the following specimen types are you interested in migrating to Arctos (check all that apply)?
Earth,Sciences
On average, how many specimens have been added to the collection(s) annually over the past 5 years?
~100
How do you expect this rate of growth to change in the foreseeable future?
Increase
What software do you currently use to manage specimen data (e.g., e.g., Access, Filemaker Pro, Excel, Specify-indicate which version, etc.)?
Access, Excel
How are your data structured in your current information system (flat table, related tables, disjoined tables, etc.)?
Everything can be converted into flat table format
Do you use controlled vocabularies or authority files for the following kinds of data (check all that apply)?
Agents,Taxonomy,Geography,Specimen Parts
Do you allow free text data entry for the following kinds of data (check all that apply)?
Agents,Taxonomy,Geography,Specimen Parts
Is it possible to bypass the controlled vocabularies or authority files? Explain
Yes, everything can be edited.
Please expand on how you deal with agents, taxonomy, geography, and/or specimen parts.
All of these are uniquely designated. We have three categories associated with each specimen number: isolated, associated (same individual but not articulated), and articulated---
How do you deal with tissues in your collection?
Tissues are treated as parts of a specimen, entered in free-form text.,Tissues are entered as free-form text in a remarks or comment field.
Describe any other details about how you deal with tissues currently, or plan to deal with them in the future.
We occasionally develop thin/histological sections of fossil specimens that will be catalogued, and housed, with the original source specimen.
Do you use machine-readable labels (such as barcodes) to digitally track any objects in your collections?
no
Describe any details about you incorporate barcodes into your current system, or whether you plan to deal with them in the future.
N/A
Describe how you deal with locality information (including coordinates, if any) in your current collection management system.
We have assigned locality numbers in each year of our collecting expeditions and associate them with waypoint information collected from mobile GPS units (latitude, longitude). The locality numbers are in the form MAD YYNN, where MAD stands for Madagascar, YY for the year of the expedition, and NN for the locality number in that year.
Approximately what proportion of your locality data are georeferenced with latitude/longitude coordinates?
~95%
Describe the kinds of metadata that you store with your coordinate information (e.g., datum, GPS error, extent, maximum uncertainty, georeferencing method, etc.)
We use datum but do not record GPS error or maximum uncertainty. All of our coordinates are x, y, and, in the case of quarries where stratigraphic level is important, z.
For the following transaction types, indicate whether you have digital information that would need to be formatted and imported? (check all that apply)
Loans,Accessions,Permits
Describe generally how you deal with transactions (loans, accessions, permits) in your current system.
We have a collaboration agreement between the Denver Museum of Nature & Science (DMNS) and the University of Antananarivo (UA) that stipulates that all holotypes and one-half of the remaining specimens will be accessioned at UA and that the other half of the remaining specimens will be accessioned at the DMNS. From 1993-2016, the other half was accessioned into the Field Museum of Natural History (FMNH), where project leader David Krause was a Research Associate. This was during the time that Krause was on the faculty at Stony Brook University but he is now (since 2016) Senior Curator of Vertebrate Paleontology at DMNS. All transactions were carried out by Krause and assistants. By agreement, all UA specimens will be returned to UA upon completion of study.
Other than basic “label data” (who/what/when/where), what other kinds of information (if any) is recorded about your specimens (e.g., citations in publications, GenBank numbers, projects, etc.)?
We will make a concerted effort to link all published specimens to lists (or figures) in publications, of which there are over 100 (excluding abstracts). We also hope to include photographs of each catalogued specimen.
Do you have digital media in your current system?
yes
Indicate how you plan to store digital media that are linked to data in Arctos.
We need storage for digital media through Arctos.,Our digital media are stored and accessible via an external web service.
Do you have someone familiar with the collection who can assist in migrating data to Arctos?
yes
Please describe any permission or security issues that would prevent us from accessing your data directly if necessary for data migration?
Not to our knowledge for data migration itself, but once the data are entered, we do not want to have locality information accessible without request.
Do you have an annual budget available for database support?
yes
Please add any other comments or questions that you have re: Arctos or your collection(s).
There are complexities related to the fact that this collection has been divided between UA and FMNH. Going forward, it will be divided between UA and DMNS. However, through discussions with John Demboski and Andy Doll, we are hoping to use Arctos ONLY for the UA part of the collection but be able to link to entries for specimens catalogued into the FMNH and DMNS collections, both of which are catalogued in the EMu/IMu system. All told, we anticipate having <10,000 specimens to catalogue for UA.

**Comment by Nicole-Ridgwell-NMMNHS** [comment]
I'd be willing to help out on the paleo end of things - we've been working on the data structure for paleo for our specimens and I am familiar with the changes that are in progress.

**Comment by Jegelewicz** [comment]
Me too!

**Comment by acdoll** [comment]
Thank you both! I'll put you down and will be contacting you when we're ready to move some data.
