### ISSUE TITLE
Utah Museum of Natural History

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#3]
No jotform submission but have been in discussion (prior to developing the jotform questionnaire) about moving their collections to Arctos. Eric Rickart will send mammal and herp data files (Excel) prior to iDigBio workshop in April 2016. Dusty and Carla will plan to meet with Eric Rickart and Shannen Robson at the workshop.

**Comment by ccicero** [comment]
I created the eml files for umnh_bird, umnh_mamm, and umnh_herp in the ArctosForVertNet dropbox folder.

**Comment by campmlc** [comment]
Is umnh entomology also coming in?

**Comment by ccicero** [comment]
They are in GBIF already, looks like they are serving their data through Symbiota. I haven't had any discussions with them about Arctos.

**Comment by ccicero** [comment]
https://github.com/VertNet/Tasks/issues/156
https://github.com/VertNet/Tasks/issues/155
https://github.com/VertNet/Tasks/issues/154

**Comment by ccicero** [comment]
Birds, mammals, and herps published to VertNet IPT 2017-09-26, and harvested/indexed to portal 2017-10-19.
