### ISSUE TITLE
UNR - University of Nevada, Reno MOU

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#35]
Need to draft MOU.

**Comment by Jegelewicz** [comment]
@ccicero please upload any documentation we have and provide contact information.

**Comment by ccicero** [comment]
Sorry, no MOU done for UNR. Contact is Dr. Chris Feldman, a former UCB undergrad  with close ties to the MVZ. Most discussion was done by phone before we really had a formal process, and Carol and I spent time with their students helping to migrate data. We need to do an MOU and invoice.

**Comment by Jegelewicz** [comment]
Draft created and shared for editing:

Chris,

Hello! I am the treasurer for the Arctos Consortium and it has come to my attention that we do not have a signed memorandum of understanding (MOU) with the University of Nevada, Reno for membership in Arctos.

I have prepared a draft MOU which requires some additional information from you (highlighted in yellow). This document is in a shared dropbox to which you will receive an invitation. Please review the MOU and edit as necessary. The document is set to track changes so that I can review your edits.

If you are not the person at UNR who will sign the MOU, please add the name and information of the person who will sign in the Key Personnel section and change the signature line at the end of the document.

If you have any questions, please contact me at this email address.

Thank you!
