### ISSUE TITLE
USFWS Forensics Laboratory

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#42]
Received Initial Questionnaire 20 Jun 2018.
[USFWS_Forensics_Lab_20180620.pdf](https://github.com/ArctosDB/new-collections/files/2120958/USFWS_Forensics_Lab_20180620.pdf)

**Comment by Jegelewicz** [comment]
Email from Ariel Gaffney at USFWFL to Chris Witt

We’ve finally gotten permission to move to Arctos and some money to do it! It’s only taken a year and a half of talking to them. I talked to Pepper and got him on board and when he visited MVZ earlier this year he chatted with Carla Cicero and both he and I have strongly encouraged the move to Arctos, if they’ll have us. Hehe. So we’re making the move, while we have the ball rolling! All of us at the lab want to be able to move to a working, searchable, useable and way more organized system. 

Our collection is in rougher shape than we’d like, but we figured we’d start the process. I saw the Arctos group has updated the process so today we filled out the questionnaire and I’m working like crazy to make at least the bird database more uniform to make migration easier. And our mammal collection is following, but is in worse shape than the birds. So we’re not sure if we can migrate the bird database and the herp databases first and follow with the mammal database when that has had a little more attention? Or if we should bite the bullet and do it all at once. I think we could use a little more info on how the migration process works. 

So we’re slowly figuring out the next steps. I think the big next step is to ask where the process goes from here? It sounds like we get a mentor (someone like you) to show us the ropes when it comes to data migration? Or is there someone in particular who is involved in helping move our current databases into Arctos, to help figure out what we need to do on our end to make that more feesible? 

We still have the other paperwork on the website to fill out and lots of data cleanup to do. (ie I think we have 5 ways of saying Spread Wing, but by tomorrow we’ll have one). We have to chat with government legal people for the MOU, apparently that could be a logistical nightmare- but we’re going to read it again and talk with our Director about whether he thinks the MOU will be an issue. 

I think a video or just a phone call with all of us would be really appreciated and help us all get on the same page. 

So excited to get to move to Arctos!  :-)

Ariel

**Comment by Jegelewicz** [comment]
On call with team from USFWSFL today: Johnnie French, Pepper Trail, Ariel Gaffney (fromer MSB), Rachel Jacobs, +1

Discussed taxonomy, identifications, encumbrances, parts, attributes, etc. Committed to Arctos and will request MOU.

**Comment by ccicero** [comment]
We need to follow up on this collection. I think the next step is to draft a MOU? @Jegelewicz

**Comment by Jegelewicz** [comment]
See the [project](https://github.com/ArctosDB/new-collections/projects/8). MOU has been sent.
