### ISSUE TITLE
NFWFL Mentor needed

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#43]
Assign collection mentor

Default = AWG Chair or Vice-Chair

AWG member can volunteer to act as primary contact, especially if they have similar collections or specific knowledge about a collection; can serve as ‘in kind support’ for collections to help offset costs

**Comment by Jegelewicz** [comment]
I will mentor their reptile collection migration. @ccicero will mentor birds. Others assigned as needed.

**Comment by campmlc** [comment]
Mariel Campbell as AWG Vice-Chair will assist with mammals and as needed.
