### ISSUE TITLE
USFWSLS Contact letter

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#44]
Standard Contact Letter
Send standard letter (https://docs.google.com/document/d/1m-lq77WnQpT_6-ClCQfwfqjxP4ETlGAhqh_YXGS0vys/edit) to new collection contact to provide info on documentation, webinars, working group, newsletter, GitHub (have them join and follow), etc as well as Arctos contact info and next steps (complete Draft MOU)

**Comment by Jegelewicz** [comment]
Awaiting info on which link to send for joining Arctos.

**Comment by dustymc** [comment]
https://arctos.database.museum/new_collection.cfm
