### ISSUE TITLE
Angelo State billing information

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#49]
Send billing information to Arctos Treasurer and invoice for year one.

**Comment by Jegelewicz** [comment]
Waiting to hear from Dianna - who to email invoice to.

**Comment by Jegelewicz** [comment]
Dianna,

I have attached the final Signed MOU and Modification.

Next step is for me to send an invoice for $105.00. It will come from Rauthiflor. Should I have it sent to your email?

Thanks!

Teresa J. Mayfield-Meyer
Arctos Treasurer

> Yes that will work. Rauthiflor is the third party through which we pay, will that require a secondary contract? Or I can ask them.
>  
> Thanks!
> 

Dianna

**Comment by Jegelewicz** [comment]
> John,
> 
> Please send Angelo State their initial bill. It is marked as "send" in the Google sheet.
> 
> Thanks!
> 

Teresa J. Mayfield-Meyer
Arctos Treasurer

**Comment by tucotuco** [comment]
Invoice RF0068 sent out on 2019-03-19.

**Comment by Jegelewicz** [comment]
Paid
