### ISSUE TITLE
University of Alabama Natural History Museum

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#6]
[Univ_Alabama_20161013.pdf](https://github.com/ArctosDB/new-collections/files/549360/Univ_Alabama_20161013.pdf)

**Comment by ccicero** [comment]
Phone conversation on 22 Feb 2017. Answered general Arctos questions.

**Comment by ccicero** [comment]
Set Mary Beth Prondzinski to do testing on 20 Mar 2017.

**Comment by ccicero** [comment]
Per email 11 May 2017:

Hi John and Mary Beth - I am copying Dusty here, but there are two sets of codes you need to consider. One is the institution code = ALMNH (to be confirmed by your Director). All collections registered at GRBIO and created in Arctos will be under that institution code. 

Separate from the institution code is the collection code. This is typically a 3-4 letter code for the type of collection. The combination of the institution code and collection code will form the GUID prefix, e.g., all bird specimens in MVZ are identified by the prefix MVZ:Bird and that is followed by the catalog number to identify the individual specimen, e.g., http://arctos.database.museum/guid/MVZ:Bird:180000

You can look at the Arctos portal to see how other institutions have designated their collections. Ideally, all collections of the same type would have the same code - e.g., 'Bird' for all bird collections. This is also used for searching in VertNet, GBIF, etc. 

If the different paleo collections have unique catalog numbers, then they should be in different collections with their own code. That way, you can have a specimen with the same number but in a different collection and it would have a unique GUID.

I think it's better to keep the modern vert collections separate.

Here is what I would recommend, for consistency with other collections in Arctos (codes and questions in bold). Probably UAM and UTEP are the most comparable in terms of the breadth of collection types.

Easy ones:
Entomology - Ento
Herpetology - Herp
Ichthyology - Fish
Ornithology - Bird
Mammalogy - Mamm
Invertebrate Zoology - Inv

Questions:

Vertebrate Paleontology
Invertebrate Paleontology
Paleobotany
Geology
UAM uses 'ES' for both Paleontology and Geology, with those forming separate subcollections. UTEP also uses ES for paleo. Can you provide more details on how these collections are currently managed. Do they have separate catalogs? 

 
History
Art and Ethnology
UAM has History and Ethnology under EH, with a separate code for Art; can you provide more details on what's in these two collections and how they are managed/cataloged?

Osteology
Human Osteology
UTEP has a separate osteology collection for herps. We had a lot of discussion about that and went with HerpOS as the collection code. What is in the Osteology and Human Osteology collections, and how are those managed? We could go with something like OS for Osteology and HOS for Human Osteology? But this is totally open for discussion.

Archives
Can you provide more details on this? We don't have separate collections for Archives in Arctos, but we do manage them as documents and/or media that are related to other records in Arctos. This would be good to discuss at SPNHC - I will be there along with our Archivist Christina Fidler; we will be presenting on a workflow for field notes, and I am hoping to talk about field notes (and archives more generally) at an Arctos meeting that we're trying to organize. 

If it would help, we can try and schedule a call to discuss this.

Best,
Carla


On Wed, May 10, 2017 at 1:04 PM, Abbott, John <jabbott1@ua.edu> wrote:
Hi Carla,

Hi Carla,
 
We are excited to finally get our collections on-line. I have a couple of questions. With respect to GRBIO. I will add our additional "institution collections,” but are there a set of codes we should be using for Arctos? And what are the constraints/recommendations regarding these? Here is a snapshot of our historical situation -
 
Vertebrate Paleontology
Invertebrate Paleontology
Paleobotany
Invertebrate Zoology
Entomology
Herpetology
Ichthyology
Geology
History
Art and Ethnology
Ornithology
Osteology
Mammalogy
Human Osteology
Archives
 
I am considering combining all three paleo collections into just Paleontology given their size. But will that work for Arctos (i.e. are there set codes we need to use and if so what are they?). What is your recommendation on the Paleobotany…will people go to paleo or botany to look up records? We don’t have a botanical collection, so it has always been associated with paleo here.
 
I was also considering combining the ornithology, mammalogy, herpetology and icthyology collections together into a vertebrate zoology collection because they aren't big and won’t be growing. Thoughts on how that would fit into the Arctos schema?
 
Thanks,
John
John C. Abbott, Ph.D.
Director of Museum Research and Collections

University of Alabama Museums 
The University of Alabama
355 Mary Harmon Bryant
Box 870340 
Tuscaloosa, AL 35487 
Phone 205-348-0534 | Fax 205-348-9292
jabbott1@ua.edu | http://almnh.ua.edu/

**Comment by ccicero** [comment]
Also added to email:

Another important point to add. Attribute types are also code table controlled, which allows us to (e.g.) select attributes specific to that collection type (e.g., molt for birds) and not see attributes for other types of collections (e.g., carapace length for herps).

You can look at all of the different attribute types by collection code here:
http://arctos.database.museum/info/ctDocumentation.cfm?table=CTATTRIBUTE_TYPE

There is also an 'Arc' code for archaeological collections.

**Comment by ccicero** [comment]
**Collections in Process:**
Invert Paleo - waiting on Mary Beth
Paleo Botany - waiting on VertNet?
Vert Paleo - waiting on VertNet
Invert Zool - waiting on VertNet

Net to tackle = Entomology

Birds and Mammals - nothing done yet.

**Comment by Jegelewicz** [comment]
[Draft MOU](https://drive.google.com/file/d/1_F9YkNzmIV53dCfxvN6-e7IGFnCRsMEJ/view?usp=sharing
) sent to Arctos contact and Steering Committee Chair.

**Comment by dbloom** [comment]
ALMNH PaleoBotany CSV sent to @dustymc for import into Arctos. Please let me know if there are any issues with this process. VertPaleo and InvertPaleo should follow shortly.

**Comment by Jegelewicz** [comment]
[Draft MOU](https://drive.google.com/open?id=1_F9YkNzmIV53dCfxvN6-e7IGFnCRsMEJ) sent to John Abbott
