### ISSUE TITLE
DMNS Parasites

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#7]
New collection DMNS:Para added to Arctos 27 Oct 2016. Once data are entered, need to create metadata and add to VertNet IPT. Also need to do this for DMNS Herps
@dustymc @laurarussell

**Comment by ccicero** [comment]
Also need to do this for DMNS Herps

**Comment by acdoll** [comment]
If you can show me how to add this metadata I would then be happy to help with other new collections.

**Comment by ccicero** [comment]
Sure Andrew (or do you go by Andy), I'd be happy to do that. I can arrange to show you and Mariel. Let me hear back from Laura first on the one I just did.

**Comment by acdoll** [comment]
Sounds good. I do go by Andy.

**Comment by acdoll** [comment]
I've added an eml.xml file to the dropbox for this one.

**Comment by ccicero** [comment]
Looks good, thanks!

**Comment by ccicero** [comment]
https://github.com/VertNet/Tasks/issues/539

**Comment by ccicero** [comment]
Published to VertNet IPT 2017-09-14.
