### ISSUE TITLE
Bell Museum of Natural History

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#8]
Questionnaire submitted, and initial contact made.
[Bell_Museum_20161026.pdf](https://github.com/ArctosDB/new-collections/files/562977/Bell_Museum_20161026.pdf)

**Comment by Jegelewicz** [comment]
> Hi Carla:
> 
> I just filled out the prospective collection form, noting that we needed director approval….  And then I saw the email from our director approving that we can join Arctos!  So, we are ready to start this process just as soon as you are.  We’re excited!
> 

All the best,
Sharon


____________________________
Sharon Jansa
Professor, Ecology, Evolution, and Behavior
Director of Graduate Admissions, EEB
Curator of Mammals, Bell Museum of Natural History
University of Minnesota
