### ISSUE TITLE
Arkansas CBC Billing

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#88]
Send billing information to Arctos Treasurer and submit initial invoice.

**Comment by Jegelewicz** [comment]
Pre bill email sent.

> Travis and Kari,
> 
> Your initial annual financial contribution for Arctos is $105.00. Please review the attached documentation used to calculate this amount and let me know if there appear to be any errors by Monday August 19, 2018. If I do not hear from you by that date, you will be invoiced for the amount above which will cover your 2018-2019 annual financial contribution to the Arctos Consortium.
> 
> Thank you for being a member!

**Comment by Jegelewicz** [comment]
> John,
> 
> Please prepare and send an invoice to Travis at Arkansas State. I changed their status to send in the Google sheet.

Thanks!

**Comment by tucotuco** [comment]
Sent.

**Comment by Jegelewicz** [comment]
Paid
