### ISSUE TITLE
Burke Museum - Mammals

### ISSUE THREAD

**Issue by ccicero** [ArctosDB/new-collections#9]
Jeff Bradley emailed Joe Cook on 16 Dec 2016 indicating their interest in moving to Arctos. Dusty needs a copy of their data. Need to follow up in January 2017.

**Comment by dustymc** [comment]
They've agreed to join Arctos.

Dave has their data, will run it through the vertnet migrators.

@lkvoong created the collection

**Comment by dustymc** [comment]
vertnetted data at https://www.dropbox.com/sh/nrs4rvg1cd9yaf0/AAC9anLVHT1W9WJ3XLizBBKpa?dl=0

**Comment by dustymc** [comment]
starting import to Arctos process

**Comment by ccicero** [comment]
Data in Arctos as of 31 Aug 2017.
https://arctosdb.org/mammal-collection-from-the-university-of-washington-burke-museum-joins-arctos/

**Comment by ccicero** [comment]
Talked with Dave Bloom today, will work on publishing this resource to VertNet IPT (hopefully this week).

**Comment by ccicero** [comment]
UWBM Mammals published to VertNet IPT 2017-10-31.
