### ISSUE TITLE
Arkansas CBC Institution Acronym

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#90]
Institution to register at GRBIO http://grbio.org/

**Comment by Jegelewicz** [comment]
Per discussion with @campmlc they need to decide if they want separate acronyms for verts and herbarium or if they will combine into ACBC.

**Comment by campmlc** [comment]
Finalized decision on Arkansas State collection portal and guids:

Delete the ACBC:Herb collection portal.

The multi-collection portal should be "Arkansas Biodiversity Collections (ABDC)"
The herbarium will be under the institutional acronym STAR, with the following guids:
              STAR:Herb
              STAR:Alg
The zoological collections will be under the institutional acronym ASUMZ, with the following guids:
              ASUMZ:Herp
              ASUMZ:Mamm
              ASUMZ:Ento
              ASUMZ:Bird
              ASUMZ:Fish
         Also need to establish collections for inverts, parasites, and tissues, this is pending.

**Comment by campmlc** [comment]
Closing, moving to #91
