### ISSUE TITLE
Arkansas CBC GitHub and AWG membership

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/new-collections#92]
Collection mentor to assist with Github registration if not already done; access to issues, documentation.

**Comment by Jegelewicz** [comment]
@campmlc are these guys connected via AWG and GitHub yet?

**Comment by Jegelewicz** [comment]
> Diana,
> 
> Hello! As we proceed with your data migration, it is much easier for us to hold all of the discussion in GitHub, where the entire community can participate and potentially help when Mariel is not available.
> 
> As far as I know, you have not created a GitHub account. Instructions for doing this can be found [here](https://handbook.arctosdb.org/how_to/How-to-Use-Github-for-Arctos.html). Once you have created your account, please email me with your GitHub username and I will invite you to the Arctos Users team. From that point on we should conduct all of your data migration discussion in GitHub.
> 
> One quick think I noticed in your conversation with Mariel:
> The part "cast" would not be appropriate for your footprint. The definition of cast as a part in Arctos is: "A fossil formed when an animal, plant, or other organism dies, its flesh decays and bones deteriorate due to chemical reactions; minerals gradually enter into the cavity, resulting in a cast, also called a mold fossil, which is in the general form of the original organism". Which does not fit what you have. (BTW, if you want to see the definitions of the parts, you can find them [here](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTSPECIMEN_PART_NAME).
> 
> See our [documentation for trace fossils](http://handbook.arctosdb.org/how_to/How-To-Catalog-Fossil-Material.html#trace-fossils). I think this method would be appropriate - I know "trace fossil" doesn't fit here, but we can have a discussion about what the evidence of a beaver should actually be called (perhaps "track" : a footprint whether recent or fossil).
> 
> Let me know once you are in GitHub!
> 
> Adios,
> 

Teresa J. Mayfield-Meyer
It's not dead if it has data!

**Comment by campmlc** [comment]
Yes.
